//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomersTable()
        {
            this.SalesTable = new HashSet<SalesTable>();
        }
    
        public int CUSTOMERID { get; set; }
        [Required(ErrorMessage = "Required field cannot be left blank!")]
        [StringLength(50,ErrorMessage = " Please enter up to 50 characters.")]
        public string CUSTOMERNAME { get; set; }
        public string CUSTOMERSURNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTable> SalesTable { get; set; }
    }
}
