//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcStockEntities : DbContext
    {
        public MvcStockEntities()
            : base("name=MvcStockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesTable> CategoriesTable { get; set; }
        public virtual DbSet<CustomersTable> CustomersTable { get; set; }
        public virtual DbSet<ProductsTable> ProductsTable { get; set; }
        public virtual DbSet<SalesTable> SalesTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
