//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTable
    {
        public int SALEID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<byte> PIECE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual CustomersTable CustomersTable { get; set; }
        public virtual ProductsTable ProductsTable { get; set; }
    }
}
